### PR TITLE
add ci setup

### PR DESCRIPTION
**Pull request by notspiff**
Do you want these setups?

### CODE REVIEW

**Comment by garbear** [comment]
Which CI systems are they hooked up to?

**Comment by notspiff** [comment]
travis and appveyor

**Comment by garbear** [comment]
Sure, lets get this building in both

**Comment by notspiff** [comment]
i'm not entirely sure how organization access works, let's see if i can figure it out.

**Comment by notspiff** [comment]
i have it setup for travis, but for appveyor it requires manual registration. you should sit on that login, please do.

**Comment by notspiff** [comment]
ref http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

**Comment by garbear** [comment]
What should I do? I created an account and confirmed the email but it says "Incorrect email or password."

**Comment by notspiff** [comment]
Uhm no idea i always used github sign on..

**Comment by garbear** [comment]
I created an AppVeyor account with by github profile. I'll merge this and try launching a test build

**Comment by notspiff** [comment]
For later we need to update status links in readme's

**Comment by notspiff** [comment]
does this actually build on windows on a local machine? i wonder if those prebuilt stuffs need some preparatory things done by the depends setup? would have to be extracted from there for sure, we cannot download all depends. @Montellese? ref https://ci.appveyor.com/project/garbear/game-libretro-hatari

**Pull request merged**
